### ISSUE TITLE
Lasted changes are not publish on npm 

### ISSUE THREAD

**Issue by chetandhembre** [bigcompany/http#2]
I think latest changes to this modules are not publish to npm, especially after this commit. https://github.com/bigcompany/http/commit/c5ce91c63fbe85ba078f35fefaf72ddfd32f2475

Can you publish it as I can not run worker of [hook.io](https://github.com/bigcompany/hook.io) ?

**Comment by Marak** [comment]
The best thing to do would be point your `package.json` to use the master branch of `http`.

Kinda like: https://github.com/bigcompany/hook.io/blob/master/package.json#L21

Thanks for taking the time to setting up hook.io locally. Any changes you make to get it working should be merged back to the master branch.

:-)

**Comment by chetandhembre** [comment]
yeah .. I just did that
